[package]
name = "lancy-zones"
version = "0.1.1"
edition = "2024"

[dependencies]
serde_json = "1.0.140"
serde = {version = "1.0.219", features = ["derive"]}
x11rb = {version = "0.13.1", features = ["shape", "xinput", "xfixes", "randr"]}
clap = { version = "4.5.37", features = ["derive"] }
